### ISSUE TITLE
It's not downloading when path has interrogation

### ISSUE THREAD

**Issue by anthonyaquino83** [muhamed-didovic/vmdown#2]
Hi Muhamed, I'm using this good scrapper to download Vuemastery content but when the path has an interrogation, this error appears, can you fix it please?
Example:

`Error thrown [Error: ENOENT: no such file or directory, open 'D:\www\vmdown\videos\progressive-web-apps-vue-3\puppeteer\screenshots\1. What are progressive web apps?.png'] {

  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\www\\vmdown\\videos\\progressive-web-apps-vue-3\\puppeteer\\screenshots\\1. What are progressive web apps?.png'
}`

**Comment by muhamed-didovic** [comment]
hey @anthonyaquino83, let me see if it works still as it should :)

**Comment by muhamed-didovic** [comment]
hey @anthonyaquino83, pull or updated to new version I made some changes to scrapers and let me know :)

**Comment by anthonyaquino83** [comment]
> hey @anthonyaquino83, pull or updated to new version I made some changes to scrapers and let me know :)

Hi Muhamed! Thank you very much for fixing it, now it's downloading fine but now the -v false flag is not working, it always download videos. 😁

**Comment by muhamed-didovic** [comment]
hey @anthonyaquino83 pull new version and let me know :)

**Comment by anthonyaquino83** [comment]
> hey @anthonyaquino83 pull new version and let me know :)

It's fixed now! Thanks! 😊
