### ISSUE TITLE
Stuck in one download

### ISSUE THREAD

**Issue by JaberWiki** [muhamed-didovic/vmdown#4]
@muhamed-didovic bro plz update

**Comment by muhamed-didovic** [comment]
sure, you have the error?

**Comment by muhamed-didovic** [comment]
@JaberWiki pushed new version...

**Comment by JaberWiki** [comment]
@muhamed-didovic ok will check when I will free.

**Comment by JaberWiki** [comment]
@muhamed-didovic  now facing this issue
![image](https://github.com/muhamed-didovic/vmdown/assets/55241455/54b8c5b6-40ef-418d-b30a-040e9086b10f)

**Comment by JaberWiki** [comment]
@muhamed-didovic  check this issue too
![image](https://github.com/muhamed-didovic/vmdown/assets/55241455/77174072-5bbd-4f66-a762-4d296768055f)
