### ISSUE TITLE
if there is any *&* symbol in url its skipping

### ISSUE THREAD

**Issue by JaberWiki** [muhamed-didovic/vmdown#5]
for example [https://www.vuemastery.com/courses/unit-testing-vue-3/testing-props-&-user-interaction-vue-3](https://www.vuemastery.com/courses/unit-testing-vue-3/testing-props-&-user-interaction-vue-3)

@muhamed-didovic

**Comment by muhamed-didovic** [comment]
@JaberWiki pushed new version

**Comment by aynaitlamine** [comment]
@muhamed-didovic it's solved
